version: 2

models:
  - name: stg_service_requests
    description: "Staging model for cleaned and enriched service request data for call center"
    columns:
      - name: request_id
        description: "Unique ID for each service request"
        tests:
          - not_null
          - unique

      - name: opened_date
        description: "Timestamp when request was opened"
        tests:
          - not_null
          - is_valid_timestamp

      - name: closed_date
        description: "Timestamp when request was closed"
        tests:
          - is_valid_timestamp

      - name: closed_flag
        description: "Boolean flag; true if request is closed"

      - name: duration_days
        description: "Days between opened_date and closed_date (or between opened_date and NOW if request is not closed)"

      - name: request_title
        description: "Name or title of the service request"

      - name: request_description
        description: "Text description of the request"

      - name: request_location
        description: "Address or location of the service request"

      - name: load_ts
        description: "Timestamp when model was run"