version: 2

models:
  - name: stg_service_requests
    description: "Staging model for cleaned and enriched service request data for call center"
    columns:
      - name: request_id
        description: "Unique ID for each service request"
        tests:
          - not_null
          - unique

      - name: opened_date
        description: "Timestamp when request was opened"
        tests:
          - not_null
          - is_valid_timestamp

      - name: closed_date
        description: "Timestamp when request was closed"
        tests:
          - is_valid_timestamp

      - name: closed_flag
        description: "Boolean flag; true if request is closed"
        tests:
          - accepted_values:
              values: [true, false]

      - name: duration_days_open
        description: "Days between opened_date and closed_date (or between opened_date and NOW if request is not closed)"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10000
          # - dbt_utils.expression_is_true:
          #     expression: "duration_days >= 0"

      - name: request_title
        description: "Name or title of the service request"

      - name: request_description
        description: "Text description of the request"

      - name: request_location
        description: "Address or location of the service request"

      - name: load_ts
        description: "Timestamp when model was run"
        tests:
          - not_null