version: 2

# this can likely be removed. keeping it as of now, 10/30, in the event that something breaks:
# sources:
#   - name: raw
#     database: ed_analytics
#     schema: raw
#     tables:
#       - name: service_requests
#         description: "Raw service requests loaded from CSV"
sources:
  - name: raw
    database: ANALYTICS_DB
    schema: raw
    tables:
      - name: service_requests
        loaded_at_field: load_ts
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}